routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use App\Models\Cart;
use App\Models\Product;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class,'index'])->name('client.home');


Route::get('product', [ClientProductController::class,'index'])->name('client.products.index');
Route::get('product-detail/{id}', [ClientProductController::class,'show'])->name('client.products.show');

Auth::routes();

Route::middleware('auth')->group(function(){
    Route::post('add-to-cart', [CartController::class,'store'])->name('client.product.show');

});
Route::middleware('auth')->group(function(){
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard'); 
    
Route::resource('roles', RoleController::class  );
Route::resource('users', UserController::class  );
Route::resource('categories' , CategoryController::class, ['index']);
Route::resource('products', ProductController::class);
Route::resource('coupons', CouponController::class);

});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Models\Role as ModelsRole;

class Role extends ModelsRole
{
    use HasFactory;

    protected $fillable = [
        'name',
        'display_name',
        'group',
        'guard_name'
    ];
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Roles\CreateRoleRequest;
use App\Models\Permissions;
use App\Models\Permisson;
use App\Models\Role;
use Illuminate\Http\Request;
use Spatie\Permission\Commands\CreateRole;
use Spatie\Permission\Contracts\Permission as ContractsPermission;
use Spatie\Permission\Models\Permission;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::latest('id')->paginate(3);
        return view('admin.roles.index' , compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all()->groupBy('group');
        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRoleRequest $request)
    {
        $dataCreate = $request->all();
        $dataCreate['guard_name'] = 'web';
        $role  = Role::create($dataCreate);
        $role->permissions()->attach($dataCreate['permission_ids']); 
        return to_route('roles.index')->with(['message' => 'Create success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::with('permissions')->findOrFail($id);
        $permissions = Permission::all()->groupBy('group');
        return view('admin.roles.edit', compact('role','permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);
        $dataUpdate = $request->all();
        $role->update($dataUpdate);
        $role->permissions()->sync($dataUpdate['permission_ids']); 

        return to_route('roles.index')->with(['message' => 'Update success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Role::destroy($id);
        return to_route('roles.index')->with(['message' => 'Delete success']);
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.dashboard.index')
@section('title', 'Create Roles')
@section('content')
    <div class="card">
        <h1>Create Role</h1>

        <form action="{{route('roles.store')}}" method="post">
            @csrf 
            <div class="input-group input-group-static mb-4">
                <label>Name</label>
                <input type="text" value="{{old('name')}}" name="name" class="form-control">

                @error('name')
                    <span class="text-danger">{{$message}}</span>
                @enderror

            </div>

            <div class="input-group input-group-static mb-4">
                <label>Display Name</label>
                <input type="text" value="{{old('display_name')}}" name="display_name" class="form-control">

                @error('display_name')
                    <span class="text-danger">{{$message}}</span>
                @enderror
            </div>
            <div class="input-group input-group-static mb-4">
                <label  class="ms-0">Group</label>
                <select name="group" class="form-control">
                    <option value="system">System</option>
                    <option value="user">User</option>
                </select>

                @error('group')
                    <span class="text-danger">{{$message}}</span>
                @enderror
            </div>


            <div class="form-group">
                <label>Permission</label>
                <div class="row">
                    @foreach($permissions as $groupName => $permisson)
                    <div class="col-5">
                            <h4>{{$groupName}}</h4>
                            <div>
                                @foreach($permisson as $item)
                                    <div class="form-check">
                                        <input class="form-check-input" name="permission_ids[]" type="checkbox" value="{{$item->id}}" >
                                        <label class="custom-control-label" for="customCheck1">{{$item->display_name}}</label>
                                    </div>
                                @endforeach
                            </div>
                    </div>
                @endforeach
                </div>

            </div>
            <button type="submit" class="btn btn-submit btn-primary">Submit</button>
        </form>
    </div>

@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.dashboard.index')
@section('title', 'Edit Roles'.$role->name)
@section('content')
    <div class="card">
        <h1>Edit Role</h1>

        <form action="{{route('roles.update', $role->id)}}" method="post">
            @csrf 
            @method('PUT')
            <div class="input-group input-group-static mb-4">
                <label>Name</label>
                <input type="text" value="{{old('name') ?? $role->name}}" name="name" class="form-control">

                @error('name')
                    <span class="text-danger">{{$message}}</span>
                @enderror

            </div>

            <div class="input-group input-group-static mb-4">
                <label>Display Name</label>
                <input type="text" value="{{old('display_name') ?? $role->display_name}}" name="display_name" class="form-control">

                @error('display_name')
                    <span class="text-danger">{{$message}}</span>
                @enderror
            </div>
            <div class="input-group input-group-static mb-4">
                <label  class="ms-0">Group</label>
                <select name="group" class="form-control" value="{{$role ->group}}">
                    <option value="system">System</option>
                    <option value="user">User</option>
                </select>

                @error('group')
                    <span class="text-danger">{{$message}}</span>
                @enderror
            </div>


            <div class="form-group">
                <label>Permission</label>
                <div class="row">
                    @foreach($permissions as $groupName => $permisson)
                    <div class="col-5">
                            <h4>{{$groupName}}</h4>
                            <div>
                                @foreach($permisson as $item)
                                    <div class="form-check">
                                        <input class="form-check-input" name="permission_ids[]" type="checkbox"
                                            {{ $role->permissions->contains('name',$item->name) ? 'checked' : ''}}
                                        value="{{$item->id}}" >
                                        <label class="custom-control-label" for="customCheck1">{{$item->display_name}}</label>
                                    </div>
                                @endforeach
                            </div>
                    </div>
                @endforeach
                </div>

            </div>
            <button type="submit" class="btn btn-submit btn-primary">Submit</button>
        </form>
    </div>

@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.dashboard.index')
@section('title', 'Roles')
@section('content')
    <div class="card">
    
        <h1>Role list</h1>
        @if(session('message'))
            <h2 class="text-primary">{{ session('message') }}</h2>
        @endif
        <div>
            <a href="{{route('roles.create')}}" class="btn btn-primary">Create</a>
        </div>
        <table class="table table-hover">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>DisplayName</th>
                <th>Action</th>
            </tr>

            @foreach ($roles as $role)
                <tr>
                    <td>{{$role -> id}}</td>
                    <td>{{$role -> name}}</td>
                    <td>{{$role -> display_name}}</td>
                    <td style="display: flex">
                        <a href="{{route('roles.edit', $role->id )}}" class="btn btn-warning">Edit</a>
                        <form action="{{route('roles.destroy', $role->id )}} " method="POST"> 
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger">Delete</button>
                        </form>

                    </td>
                </tr>
            @endforeach
        </table>
        {{$roles->links()}}
    </div>
@endsection