routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use App\Models\Cart;
use App\Models\Product;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class,'index'])->name('client.home');


Route::get('product', [ClientProductController::class,'index'])->name('client.products.index');
Route::get('product-detail/{id}', [ClientProductController::class,'show'])->name('client.products.show');

Auth::routes();

Route::middleware('auth')->group(function(){
    Route::post('add-to-cart', [CartController::class,'store'])->name('client.product.show');

});
Route::middleware('auth')->group(function(){
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard'); 
    
Route::resource('roles', RoleController::class  );
Route::resource('users', UserController::class  );
Route::resource('categories' , CategoryController::class, ['index']);
Route::resource('products', ProductController::class);
Route::resource('coupons', CouponController::class);

});

resources/views/admin/layouts/sidebar.blade.php
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
    <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
    <a class="navbar-brand m-0" href=" https://demos.creative-tim.com/material-dashboard/pages/dashboard " target="_blank">
        <img src="{{asset('admin/assets/img/logo-ct.png')}}" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold text-white">Material Dashboard 2</span>
    </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto  max-height-vh-100" id="sidenav-collapse-main">
    <ul class="navbar-nav">
        <li class="nav-item">
        <a class="nav-link text-white {{ request()->routeIs('dashboard') ? 'active bg-gradient-primary' : '' }}" href="{{ route('dashboard')}}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10">dashboard</i>
            </div>
            <span class="nav-link-text ms-1">Dashboard</span>
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-white {{ request()->routeIs('roles.*') ? 'active bg-gradient-primary' : '' }} " href="{{ route('roles.index')}}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10">table_view</i>
            </div>
            <span class="nav-link-text ms-1">Role</span>
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-white  {{ request()->routeIs('users.*') ? 'active bg-gradient-primary' : '' }}"  href="{{ route('users.index')}}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10">receipt_long</i>
            </div>
            <span class="nav-link-text ms-1">User</span>
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-white {{ request()->routeIs('products.*') ? 'active bg-gradient-primary' : '' }} " href="{{route('products.index')}}" >
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10">view_in_ar</i>
            </div>
            <span class="nav-link-text ms-1">Product</span>
        </a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-white {{ request()->routeIs('categories.*') ? 'active bg-gradient-primary' : '' }} " href="{{route('categories.index')}}">
            <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
            <i class="material-icons opacity-10">format_textdirection_r_to_l</i>
            </div>
            <span class="nav-link-text ms-1">Categories</span>
        </a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white {{ request()->routeIs('coupons.*') ? 'active bg-gradient-primary' : '' }} " href="{{route('coupons.index')}}">
                <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">format_textdirection_r_to_l</i>
                </div>
                <span class="nav-link-text ms-1">Coupon</span>
            </a>
            </li>
    </ul>
</aside>