routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use App\Models\Cart;
use App\Models\Product;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class,'index'])->name('client.home');


Route::get('product', [ClientProductController::class,'index'])->name('client.products.index');
Route::get('product-detail/{id}', [ClientProductController::class,'show'])->name('client.products.show');

Auth::routes();

Route::middleware('auth')->group(function(){
    Route::post('add-to-cart', [CartController::class,'store'])->name('client.product.show');

});
Route::middleware('auth')->group(function(){
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard'); 
    
Route::resource('roles', RoleController::class  );
Route::resource('users', UserController::class  );
Route::resource('categories' , CategoryController::class, ['index']);
Route::resource('products', ProductController::class);
Route::resource('coupons', CouponController::class);

});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use App\Http\Traits\HandleImageTrait as TraitsHandleImageTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    use HasRoles;
  
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'address',
        'gender'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\User\CreaterUserRequest;
use App\Http\Requests\User\UpdateUserRequest as UserUpdateUserRequest;
use App\Http\Requests\Users\CreateUserRequest as UsersCreateUserRequest;
use App\Http\Requests\Users\UpdateUserRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{

    protected $user;
    protected $role;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(User $user , Role $role)
    {
        $this->user = $user;
        $this->role = $role;
    }
    public function index()
    {
        $users = $this->user->latest('id')->paginate(5);
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = $this->role->all()->groupBy('group');
        return view('admin.users.create' , compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreaterUserRequest $request)
    {
        $dateCreate = $request->all();
        $dateCreate['password'] =Hash::make($request->password);
        // $dateImage['image'] = $this->user->saveImage($request);

        $user = $this->user->create($dateCreate);
        $user->roles()->attach($dateCreate['role_ids']);
        return to_route('users.index')->with(['message' => 'Create success']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->user->findOrFail($id)->load('roles');
        $roles = $this->role->all()->groupBy('group');
        return view('admin.users.edit', compact('user' ,'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateUserRequest $request, $id)
    {
        $dateUpdate = $request->except('password');
        $user = $this->user->findOrFail($id)->load('roles');
        if($request->password)
        {
            $dateCreate['password'] = Hash::make($request->password);
        }
        // $dateImage['image'] = $this->user->saveImage($request);


        $user->update($dateUpdate);
        $user->roles()->sync($dateUpdate['role_ids']);
        return to_route('users.index')->with(['message' => 'Update success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = $this->user->findOrFail($id)->load('roles');
        $user->delete();
        return to_route('users.index')->with(['message' => 'Delete success']);
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.dashboard.index')
@section('title', 'Create User')
@section('content')
    <div class="cart">
        <h1>Create User</h1>
        
            <form action="{{route('users.store')}}" method="post" enctype="multipart/form-data">
                @csrf 
                {{-- <div class="row">
                    <div class="input-group input-group-static mb-4 col-5">
                        <label>Image</label>
                        <input type="file" accept="image/*" name="image" id="image-input" class="form-control">
                        @error('image')
                            <span class="text-danger">{{$message}}</span>
                        @enderror
                        <div class="col-5">
                            <img src="" id="show-image" alt="">
                        </div>
                    </div>
                </div>  --}}
    
                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{old('name')}}" name="name" class="form-control">
    
                    @error('name')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
    
                <div class="input-group input-group-static mb-4">
                    <label>Email</label>
                    <input type="email" value="{{old('email')}}" name="email" class="form-control">
    
                    @error('email')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
    
                
                <div class="input-group input-group-static mb-4">
                    <label>Phone</label>
                    <input type="text" value="{{old('phone')}}" name="phone" class="form-control">
    
                    @error('phone')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
    
                <div class="input-group input-group-static mb-4">
                    <label>Address</label>
                    <textarea type="address" name="address" class="form-control">{{old('address')}} </textarea>
    
                    @error('address')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
                
                <div class="input-group input-group-static mb-4">
                    <label>Password</label>
                    <input type="password" name="password" class="form-control">
    
                    @error('password')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
    
                <div class="input-group input-group-static mb-4">
                    <label  class="ms-0">Gender</label>
                    <select name="gender" class="form-control">
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>
    
                    @error('gender')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
            
    
    
                <div class="form-group">
                    <label>Roles</label>
                    <div class="row">
                        @foreach($roles as $groupName => $role)
                        <div class="col-5">
                                <h4>{{$groupName}}</h4>
                                <div>
                                    @foreach($role as $item)
                                        <div class="form-check">
                                            <input class="form-check-input" name="role_ids[]" type="checkbox" value="{{$item->id}}" >
                                            <label class="custom-control-label" for="customCheck1">{{$item->display_name}}</label>
                                        </div>
                                    @endforeach
                                </div>
                        </div>
                    @endforeach
                    </div>
    
                </div>
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
      
    </div>
    <script> src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM="
        crossorigin="anonymous"></script>
    <script >
        $(() => {
            function readURL(input){
                if(input.files && input.files[0]){
                    var reader = new FileReader();
                    reader.onload = function(e){
                        $("#show-image").attr('src', e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }
            $("#image-input").change(function(){
                readURL(this);
            });
            
        });
    </script>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.dashboard.index')
@section('title', 'Edit User'.$user->name)
@section('content')
    <div class="cart">
        <h1>Create User</h1>

            <form action="{{route('users.update', $user->id)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method("PUT")
                {{-- <div class="row">
                    <div class="input-group input-group-static mb-4 col-5">
                        <label>Image</label>
                        <input type="file" accept="image/*" name="image" id="image-input" class="form-control">
                        @error('image')
                            <span class="text-danger">{{$message}}</span>
                        @enderror
                        <div class="col-5">
                            <img src="" id="show-image" alt="">
                        </div>
                    </div>
                </div>  --}}

                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{old('name') ?? $user->name}}" name="name" class="form-control">

                    @error('name')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Email</label>
                    <input type="email" value="{{old('email') ?? $user->email}}" name="email" class="form-control">

                    @error('email')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>


                <div class="input-group input-group-static mb-4">
                    <label>Phone</label>
                    <input type="text" value="{{old('phone') ?? $user->phone}}" name="phone" class="form-control">

                    @error('phone')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Address</label>
                    <textarea type="address" name="address" class="form-control">{{old('address') ?? $user->address}} </textarea>

                    @error('address')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label>Password</label>
                    <input type="password" name="password" class="form-control">

                    @error('password')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>

                <div class="input-group input-group-static mb-4">
                    <label  class="ms-0">Gender</label>
                    <select name="gender" class="form-control" value="{{$user->gender}}">
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>

                    @error('gender')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>



                <div class="form-group">
                    <label>Roles</label>
                    <div class="row">
                        @foreach($roles as $groupName => $role)
                        <div class="col-5">
                                <h4>{{$groupName}}</h4>
                                <div>
                                    @foreach($role as $item)
                                        <div class="form-check">
                                            <input class="form-check-input" name="role_ids[]"
                                            {{$user->roles->contains('id',$item->id) ? "checked" : ""}}
                                            type="checkbox" value="{{$item->id}}" >
                                            <label class="custom-control-label" for="customCheck1">{{$item->display_name}}</label>
                                        </div>
                                    @endforeach
                                </div>
                        </div>
                    @endforeach
                    </div>

                </div>
                <button type="submit" class="btn btn-submit btn-primary">Update</button>
            </form>

    </div>
    {{-- <script> src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM="
        crossorigin="anonymous"></script>
    <script >
        $(() => {
            function readURL(input){
                if(input.files && input.files[0]){
                    var reader = new FileReader();
                    reader.onload = function(e){
                        $("#show-image").attr('src', e.target.result);
                    };
                    reader.readAsDataURL(input.files[0]);
                }
            }
            $("#image-input").change(function(){
                readURL(this);
            });

        });
    </script> --}}
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.dashboard.index')
@section('title', 'Users')
@section('content')
    <div class="card">

        <h1>User list</h1>
        @if(session('message'))
            <h2 class="text-primary">{{ session('message') }}</h2>
        @endif
        <div>
            <a href="{{route('users.create')}}" class="btn btn-primary">Create</a>
        </div>
        <table class="table table-hover">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Action</th>
            </tr>

            @foreach ($users as $item)
                <tr>
                    <td>{{$item -> id}}</td>
                    <td>{{$item -> name}}</td>
                    <td>{{$item -> email}}</td>
                    <td>{{$item -> phone}}</td>
                    <td style="display: flex">
                        <a href="{{route('users.edit', $item->id )}}" class="btn btn-warning">Edit</a>
                        <form action="{{route('users.destroy', $item->id )}} " id="form-delete{{$item->id}}"
                            method="POST"> 
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger" type="submit"  data-id="{{$item->id}}">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
        {{$users->links()}}
    </div>
@endsection