routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use App\Models\Cart;
use App\Models\Product;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class,'index'])->name('client.home');


Route::get('product', [ClientProductController::class,'index'])->name('client.products.index');
Route::get('product-detail/{id}', [ClientProductController::class,'show'])->name('client.products.show');

Auth::routes();

Route::middleware('auth')->group(function(){
    Route::post('add-to-cart', [CartController::class,'store'])->name('client.product.show');

});
Route::middleware('auth')->group(function(){
    Route::get('/dashboard', function () {
        return view('admin.dashboard.index');
    })->name('dashboard'); 
    
Route::resource('roles', RoleController::class  );
Route::resource('users', UserController::class  );
Route::resource('categories' , CategoryController::class, ['index']);
Route::resource('products', ProductController::class);
Route::resource('coupons', CouponController::class);

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'parent_id',
    ];
    public function parent(){
        return $this->belongsTo(Category::class, 'parent_id');
    }

    public function childrens(){
        return $this->hasMany(Category::class,'parent_id');
    }

    public function getParentNameAttribute(){
        return optional($this->parent)->name;
    }

    public function getParents(){
        return Category::whereNull('parent_id')->with('childrens')->get(['id', 'name']);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\CreateRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $category;
    public function __construct(Category $category)
    {   
        $this->category = $category;
    }

    public function index()
    {
        $categories = $this->category->latest('id')->paginate(3);
        return view('admin.categories.index' , compact('categories'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parentCategories = $this->category->getParents();
        return view('admin.categories.create' , compact('parentCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $dateCreate = $request->all();
        $category = $this->category->create($dateCreate);

        return redirect()->route('categories.index')
        ->with(['message' => "Create new category: ". $category->name ." success"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->category->with('childrens')->findOrFail($id);
        $parentCategories = $this->category->getParents();
        return view('admin.categories.edit' , compact('category' , 'parentCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $dateUpdate = $request->all();
        $category = $this->category->findOrFail($id);
        $category->update($dateUpdate); 
        
        return redirect()->route('categories.index')
        ->with(['message' => "Update category: ". $category->name ." success"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->category->findOrFail($id);
        $category->delete(); 
        
        return redirect()->route('categories.index')
        ->with(['message' => "Delete category: ". $category->name ." success"]);
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.dashboard.index')
@section('title', 'Create Category')
@section('content')
    <div class="cart">
        <h1>Create Category</h1>
            <form action="{{route('categories.store')}}" method="post" enctype="multipart/form-data">
                @csrf 
                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{old('name')}}" name="name" class="form-control">
    
                    @error('name')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
                <div class="input-group input-group-static mb-4">
                    <label  class="ms-0">Parent Category</label>
                    <select name="parent_id" class="form-control" value="{{old('perant_id')}}">
                        @foreach ($parentCategories as $item)
                            <option value="{{$item->id}}" {{old('parent_id') == $item->id ? 'selected' : ''}}>{{$item->name}}</option>
                        @endforeach 
                    
                    </select>
    
                    @error('parent_ids')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
      
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.dashboard.index')
@section('title', 'Edit Category' .$category->name)
@section('content')
    <div class="cart">
        <h1>Edit Category</h1>
            <form action="{{route('categories.update' , $category->id )}}" method="post">
                @csrf 
                @method('PUT')
                <div class="input-group input-group-static mb-4">
                    <label>Name</label>
                    <input type="text" value="{{old('name') ?? $category->name}}" name="name" class="form-control">
    
                    @error('name')
                        <span class="text-danger">{{$message}}</span>
                    @enderror
                </div>
                @if ($category->childrens->count() < 1)
                    
                    <div class="input-group input-group-static mb-4">
                        <label  class="ms-0">Parent Category</label>
                        <select name="parent_id" class="form-control" value="{{old('perant_id')}}">
                            @foreach ($parentCategories as $item)
                                <option value="{{$item->id}}" {{(old('parent_id') ?? $category->parent_id ) == $item->id ? 'selected' : ''}}>{{$item->name}}</option>
                            @endforeach 
                        </select>
                        @error('parent_ids')
                            <span class="text-danger">{{$message}}</span>
                        @enderror
                    </div>
                @endif
                <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            </form>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.dashboard.index')
@section('title', 'Category')
@section('content')
    <div class="card">

        <h1>Categories list</h1>
        @if(session('message'))
            <h2 class="text-primary">{{session('message') }}</h2>
        @endif
        <div>
            <a href="{{route('categories.create')}}" class="btn btn-primary">Create</a>
        </div>
        <table class="table table-hover">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Parent Name</th>
                <th>Action</th>
            </tr>

            @foreach ($categories as $item)
                <tr>
                    <td>{{$item -> id}}</td>
                    <td>{{$item -> name}}</td>
                    <td>{{$item -> parent_name}}</td>
                   
                    <td style="display: flex">
                        <a href="{{route('categories.edit', $item->id )}}" class="btn btn-warning">Edit</a>
                        <form action="{{route('categories.destroy', $item->id )}} " id="form-delete{{$item->id}}"
                            method="POST"> 
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger" type="submit"  data-id="{{$item->id}}">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
        {{$categories->links()}}
    </div>
@endsection